version: "3.7"

services:
  php81:
    build:
      dockerfile: Dockerfile
      context: .docker/php/8.1
    container_name: om_et_php81
    restart: "no"
    networks:
      - om_et
    volumes:
      - ./:/repo
    working_dir: /repo

  composer:
    build:
      dockerfile: Dockerfile
      context: .docker/composer
    container_name: om_et_composer
    restart: "no"
    volumes:
      - ./:/repo
    working_dir: /repo
    command: "update -o -v"
    networks:
      - default

  phpstan:
    image: phpstan/phpstan
    container_name: om_et_phpstan
    restart: "no"
    volumes:
      - ./:/repo
    working_dir: /repo
    command: "analyze --level 5 src/"
    networks:
      - om_et

networks:
  default:
    external:
      name: "gateway"
  om_et:
    internal: true